# Создание нового заказа 1
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1
}

###

# Создание нового заказа 2
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 3
}

###

# Создание нового заказа 3
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 3,
  "product_id": 5
}

###

# Создание нового заказа 4
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 4,
  "product_id": 7
}

###

# Создание нового заказа 5
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 5,
  "product_id": 2
}

###

# Создание нового заказа 6
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 6,
  "product_id": 4
}

###

# Создание нового заказа 7
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 7,
  "product_id": 6
}

###

# Создание нового заказа 8
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 8,
  "product_id": 8
}

###

# Создание нового заказа 9
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 9,
  "product_id": 10
}

###

# Создание нового заказа 10
POST http://localhost:8000/orders/
Content-Type: application/json

{
  "user_id": 10,
  "product_id": 9
}
